fix: fix aws deps using --use-feature=2020-resolver with pip install
ekino/docker-buildbox pull request #340
Opened 2020-10-22 11:10 UTC by julienpierini

2020-10-22 13:53 UTC, Crow-EH approved these changes

2020-10-23 09:15 UTC, Mallear requested changes

2020-10-23 09:15 UTC, Mallear commented on CHANGELOG.md
> +* fix aws image dependancies
`dependencies` + add how you fixed it. The aim is to remind us to delete this when pip officialy changes its way to install deps.

2020-10-23 09:19 UTC, Mallear approved these changes

2020-10-23 09:26 UTC, merged